// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyACyoqPomUQ2vp9fjUbwc51KXHfVW82Q74',
    appId: '1:113118164530:web:03f84e7b1aae6dfce5ae2b',
    messagingSenderId: '113118164530',
    projectId: 'mobilya-asistani',
    authDomain: 'mobilya-asistani.firebaseapp.com',
    storageBucket: 'mobilya-asistani.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAmWpn_lZkzKr3Ywmcu4NoGw2H9KjjHrnQ',
    appId: '1:113118164530:android:848b8696b9b0c88ce5ae2b',
    messagingSenderId: '113118164530',
    projectId: 'mobilya-asistani',
    storageBucket: 'mobilya-asistani.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCl4R5GIt0wet7pDA3ESwMiuJIneZq4Or4',
    appId: '1:113118164530:ios:24e2eb55618d4475e5ae2b',
    messagingSenderId: '113118164530',
    projectId: 'mobilya-asistani',
    storageBucket: 'mobilya-asistani.firebasestorage.app',
    iosBundleId: 'com.example.modulApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCl4R5GIt0wet7pDA3ESwMiuJIneZq4Or4',
    appId: '1:113118164530:ios:24e2eb55618d4475e5ae2b',
    messagingSenderId: '113118164530',
    projectId: 'mobilya-asistani',
    storageBucket: 'mobilya-asistani.firebasestorage.app',
    iosBundleId: 'com.example.modulApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyACyoqPomUQ2vp9fjUbwc51KXHfVW82Q74',
    appId: '1:113118164530:web:3d1d2d2102d46962e5ae2b',
    messagingSenderId: '113118164530',
    projectId: 'mobilya-asistani',
    authDomain: 'mobilya-asistani.firebaseapp.com',
    storageBucket: 'mobilya-asistani.firebasestorage.app',
  );
}
